start cmd.exe /k mdbroker

start cmd.exe /k mdworker
start cmd.exe /k mdworker
start cmd.exe /k mdworker
start cmd.exe /k mdworker
start cmd.exe /k mdworker
start cmd.exe /k mdworker

start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
start cmd.exe /k mdclient
